name: TaskFlow CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Installer Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: backend/package-lock.json

      - name: Installer les dépendances du backend
        working-directory: backend
        run: npm ci

      - name: Lancer les tests du backend
        working-directory: backend
        run: npm test -- --passWithNoTests

      - name: Connexion à Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Construire les services
        run: docker compose -f docker-compose.yml build

      - name: Démarrer les services
        run: docker compose -f docker-compose.yml up -d

      - name: Vérifier les containers 
        run: docker compose -f docker-compose.yml ps

      - name: Publier les images
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/taskflow-backend:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/taskflow-frontend:latest