name: TaskFlow CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Installer Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: backend/package-lock.json

      - name: Installer les dépendances du backend
        working-directory: backend
        run: npm ci

      - name: Lancer les tests du backend
        working-directory: backend
        run: npm test -- --passWithNoTests

      - name: Connexion à Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Construire l'image backend
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/taskflow-backend:latest ./backend

      - name: Construire l'image frontend
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/taskflow-frontend:latest ./frontend

      - name: Publier l'image backend
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/taskflow-backend:latest

      - name: Publier l'image frontend
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/taskflow-frontend:latest